### ISSUE TITLE
Request: Icon picker 

### ISSUE THREAD

**Issue by hsantanna** [linjie997/mi9-FOD-icon#1]
Please implement an icon picker like evolutionx FOD icon picker.

**Comment by linjie997** [comment]
I don't think it's possible with a Magisk module, and also beyond my knowledge.
But I will consider in the future some way to generate the module with an icon of user choice with a script.

Example:
- Put icon in a specified folder
- Run the script
- Pff magic

This need a lot of testing by my side since I'm not familiar with Android modding world, but I hope I will find some time to do so.
Meanwhile, use either the default icon, mine or use a ROM like EvolutionX.
Thank you.

If you have some suggestion or questions, feel free to reopen the issue.
